name: De4Dot Deobfuscation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_ROOT: C:\Program Files\dotnet
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET (for Build)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build De4Dot
        shell: pwsh
        run: |
          dotnet build de4dot.netcore.sln --configuration Release

      - name: Find de4dot.exe
        id: find_exe
        shell: pwsh
        run: |
          # Search recursively for de4dot.exe.
          $exePath = Get-ChildItem -Path .\ -Filter de4dot.exe -Recurse | Select-Object -First 1
          if ($null -eq $exePath) {
              Write-Error "de4dot.exe not found. Ensure the build produced it."
              exit 1
          }
          Write-Host "Found de4dot.exe at $($exePath.FullName)"
          echo "::set-output name=exe_path::$($exePath.FullName)"

      - name: Upload de4dot.exe Artifact
        uses: actions/upload-artifact@v4
        with:
          name: de4dot_exe
          path: ${{ steps.find_exe.outputs.exe_path }}
