name: De4Dot Deobfuscation

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct URL to the DLL/EXE file to deobfuscate'
        required: true
        # Using v4 instead of v3 as requested.
        default: 'https://github.com/daisuke1227/de4dot/releases/download/untagged-70696b41b27bd1a02194/QuantumV3.dll'

jobs:
  deobfuscate:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Adjust if needed

      - name: Build De4Dot
        run: |
          dotnet build de4dot.netcore.sln --configuration Release
        shell: pwsh

      - name: Download Target File
        shell: pwsh
        run: |
          Write-Host "Downloading file from '${{ github.event.inputs.file_url }}'"
          # Use curl with -L to follow redirects.
          curl -L "${{ github.event.inputs.file_url }}" -o targetFile.dll

      - name: Run De4Dot Deobfuscation
        shell: pwsh
        run: |
          Write-Host "Deobfuscating targetFile.dll..."
          # Adjust the path to de4dot.exe if needed.
          .\bin\Release\net6.0\de4dot.exe targetFile.dll -o deobfuscated_output.dll

      - name: Upload Deobfuscated Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deobfuscated_output
          path: deobfuscated_output.dll
