name: De4Dot Deobfuscation

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'Direct URL to the DLL/EXE file to deobfuscate'
        required: true
        default: 'https://example.com/yourfile.dll'

jobs:
  deobfuscate:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'  # Adjust if needed

      - name: Build De4Dot
        run: |
          dotnet build De4Dot.sln --configuration Release
        shell: pwsh

      - name: Download Target File
        shell: pwsh
        run: |
          Write-Host "Downloading file from '${{ github.event.inputs.file_url }}'"
          Invoke-WebRequest -Uri "${{ github.event.inputs.file_url }}" -OutFile targetFile.exe

      - name: Run De4Dot Deobfuscation
        shell: pwsh
        run: |
          Write-Host "Deobfuscating targetFile.exe..."
          # Adjust the path to de4dot.exe as needed based on your build output folder.
          .\bin\Release\net6.0\de4dot.exe targetFile.exe -o deobfuscated_output.exe

      - name: Upload Deobfuscated Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deobfuscated_output
          path: deobfuscated_output.exe
